-- =====================================================
-- RoomMitra PostgreSQL Schema Reference
-- This file shows the expected database structure
-- Auto-generated by EF Core migrations
-- =====================================================

-- =====================================================
-- ENUMS (stored as INT)
-- =====================================================

-- Gender: Male=1, Female=2, Any=3
-- PreferredFood: Vegetarian=1, NonVegetarian=2, Any=3  
-- PropertyType: OneBhk=1, TwoBhk=2, ThreeBhk=3, PG=4, Shared=5
-- Furnishing: Unfurnished=1, SemiFurnished=2, Furnished=3
-- ListingStatus: Active=1, Inactive=2, Rented=3

-- =====================================================
-- TABLE: Users (AspNetUsers)
-- =====================================================
CREATE TABLE "AspNetUsers" (
    "Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "Name" VARCHAR(200) NOT NULL,
    "UserName" VARCHAR(256),
    "NormalizedUserName" VARCHAR(256),
    "Email" VARCHAR(256),
    "NormalizedEmail" VARCHAR(256),
    "EmailConfirmed" BOOLEAN NOT NULL,
    "PasswordHash" TEXT,
    "SecurityStamp" TEXT,
    "ConcurrencyStamp" TEXT,
    "PhoneNumber" VARCHAR(50),
    "PhoneNumberConfirmed" BOOLEAN NOT NULL,
    "TwoFactorEnabled" BOOLEAN NOT NULL,
    "LockoutEnd" TIMESTAMPTZ,
    "LockoutEnabled" BOOLEAN NOT NULL,
    "AccessFailedCount" INT NOT NULL,
    "Gender" INT,
    "IsVerified" BOOLEAN NOT NULL DEFAULT FALSE,
    "ProfileImageUrl" VARCHAR(500),
    "Occupation" VARCHAR(100),
    "Bio" VARCHAR(1000),
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ
);

CREATE UNIQUE INDEX "IX_AspNetUsers_Email" ON "AspNetUsers" ("NormalizedEmail");
CREATE INDEX "IX_AspNetUsers_PhoneNumber" ON "AspNetUsers" ("PhoneNumber");
CREATE INDEX "IX_AspNetUsers_IsVerified" ON "AspNetUsers" ("IsVerified");

-- =====================================================
-- TABLE: Properties
-- =====================================================
CREATE TABLE "Properties" (
    "Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "UserId" UUID NOT NULL,
    "Title" VARCHAR(200) NOT NULL,
    "Description" VARCHAR(4000) NOT NULL,
    "PropertyType" INT NOT NULL,
    "Rent" DECIMAL(18,2) NOT NULL,
    "Deposit" DECIMAL(18,2) NOT NULL,
    "AvailableFrom" DATE,
    "City" VARCHAR(100) NOT NULL,
    "Area" VARCHAR(200) NOT NULL,
    "Address" VARCHAR(500) NOT NULL,
    "Latitude" DECIMAL(10,7),
    "Longitude" DECIMAL(10,7),
    "PreferredGender" INT NOT NULL DEFAULT 3,
    "PreferredFood" INT NOT NULL DEFAULT 3,
    "Furnishing" INT NOT NULL,
    "Status" INT NOT NULL DEFAULT 1,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ,
    
    CONSTRAINT "FK_Properties_Users" 
        FOREIGN KEY ("UserId") 
        REFERENCES "AspNetUsers"("Id") 
        ON DELETE CASCADE
);

CREATE INDEX "IX_Properties_UserId" ON "Properties" ("UserId");
CREATE INDEX "IX_Properties_City" ON "Properties" ("City");
CREATE INDEX "IX_Properties_Rent" ON "Properties" ("Rent");
CREATE INDEX "IX_Properties_PropertyType" ON "Properties" ("PropertyType");
CREATE INDEX "IX_Properties_Status" ON "Properties" ("Status");
CREATE INDEX "IX_Properties_AvailableFrom" ON "Properties" ("AvailableFrom");
CREATE INDEX "IX_Properties_Search" ON "Properties" ("City", "Rent", "Status");

-- =====================================================
-- TABLE: PropertyImages
-- =====================================================
CREATE TABLE "PropertyImages" (
    "Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "PropertyId" UUID NOT NULL,
    "ImageUrl" VARCHAR(1000) NOT NULL,
    "IsCover" BOOLEAN NOT NULL DEFAULT FALSE,
    "DisplayOrder" INT NOT NULL DEFAULT 0,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ,
    
    CONSTRAINT "FK_PropertyImages_Properties" 
        FOREIGN KEY ("PropertyId") 
        REFERENCES "Properties"("Id") 
        ON DELETE CASCADE
);

CREATE INDEX "IX_PropertyImages_PropertyId" ON "PropertyImages" ("PropertyId");
CREATE INDEX "IX_PropertyImages_Cover" ON "PropertyImages" ("PropertyId", "IsCover");
CREATE INDEX "IX_PropertyImages_Order" ON "PropertyImages" ("PropertyId", "DisplayOrder");

-- =====================================================
-- TABLE: Amenities
-- =====================================================
CREATE TABLE "Amenities" (
    "Id" UUID PRIMARY KEY,
    "Name" VARCHAR(100) NOT NULL,
    "Description" VARCHAR(500),
    "Icon" VARCHAR(100)
);

CREATE UNIQUE INDEX "IX_Amenities_Name" ON "Amenities" ("Name");

-- Seed data
INSERT INTO "Amenities" ("Id", "Name", "Description", "Icon") VALUES
('11111111-1111-1111-1111-111111111111', 'WiFi', 'High-speed internet connection', 'wifi'),
('22222222-2222-2222-2222-222222222222', 'Air Conditioning', 'AC in rooms', 'ac_unit'),
('33333333-3333-3333-3333-333333333333', 'Washing Machine', 'Washing machine available', 'local_laundry_service'),
('44444444-4444-4444-4444-444444444444', 'Parking', 'Vehicle parking space', 'local_parking'),
('55555555-5555-5555-5555-555555555555', 'Gym', 'Fitness center', 'fitness_center'),
('66666666-6666-6666-6666-666666666666', 'Power Backup', 'Generator backup', 'power'),
('77777777-7777-7777-7777-777777777777', 'Water Purifier', 'RO water system', 'water_drop'),
('88888888-8888-8888-8888-888888888888', 'Refrigerator', 'Fridge available', 'kitchen'),
('99999999-9999-9999-9999-999999999999', 'TV', 'Television', 'tv'),
('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Security', '24/7 security', 'security');

-- =====================================================
-- TABLE: PropertyAmenities (Join Table)
-- =====================================================
CREATE TABLE "PropertyAmenities" (
    "PropertyId" UUID NOT NULL,
    "AmenityId" UUID NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    PRIMARY KEY ("PropertyId", "AmenityId"),
    
    CONSTRAINT "FK_PropertyAmenities_Properties" 
        FOREIGN KEY ("PropertyId") 
        REFERENCES "Properties"("Id") 
        ON DELETE CASCADE,
        
    CONSTRAINT "FK_PropertyAmenities_Amenities" 
        FOREIGN KEY ("AmenityId") 
        REFERENCES "Amenities"("Id") 
        ON DELETE CASCADE
);

CREATE INDEX "IX_PropertyAmenities_PropertyId" ON "PropertyAmenities" ("PropertyId");
CREATE INDEX "IX_PropertyAmenities_AmenityId" ON "PropertyAmenities" ("AmenityId");

-- =====================================================
-- TABLE: UserPreferences
-- =====================================================
CREATE TABLE "UserPreferences" (
    "Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "UserId" UUID NOT NULL,
    "BudgetMin" DECIMAL(18,2),
    "BudgetMax" DECIMAL(18,2),
    "PreferredCity" VARCHAR(100),
    "PreferredAreas" JSONB,
    "PreferredGender" INT,
    "PreferredFood" INT,
    "PreferredPropertyType" INT,
    "PreferredFurnishing" INT,
    "MoveInDate" DATE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "UpdatedAt" TIMESTAMPTZ,
    
    CONSTRAINT "FK_UserPreferences_Users" 
        FOREIGN KEY ("UserId") 
        REFERENCES "AspNetUsers"("Id") 
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_UserPreferences_UserId" ON "UserPreferences" ("UserId");
CREATE INDEX "IX_UserPreferences_City" ON "UserPreferences" ("PreferredCity");
CREATE INDEX "IX_UserPreferences_Budget" ON "UserPreferences" ("BudgetMin", "BudgetMax");

-- =====================================================
-- USEFUL QUERIES
-- =====================================================

-- Get properties with all details
CREATE OR REPLACE VIEW "vw_PropertyDetails" AS
SELECT 
    p."Id",
    p."Title",
    p."Description",
    p."PropertyType",
    p."Rent",
    p."Deposit",
    p."City",
    p."Area",
    u."Name" AS "OwnerName",
    u."Email" AS "OwnerEmail",
    u."PhoneNumber" AS "OwnerPhone",
    (SELECT json_agg(pi."ImageUrl") 
     FROM "PropertyImages" pi 
     WHERE pi."PropertyId" = p."Id") AS "Images",
    (SELECT json_agg(a."Name") 
     FROM "PropertyAmenities" pa 
     INNER JOIN "Amenities" a ON pa."AmenityId" = a."Id"
     WHERE pa."PropertyId" = p."Id") AS "Amenities"
FROM "Properties" p
INNER JOIN "AspNetUsers" u ON p."UserId" = u."Id"
WHERE p."Status" = 1;

-- Full-text search function (for future use)
CREATE INDEX IF NOT EXISTS "IX_Properties_FullText" 
ON "Properties" USING gin(to_tsvector('english', "Title" || ' ' || "Description"));

-- =====================================================
-- PERFORMANCE FUNCTIONS
-- =====================================================

-- Function to search properties with filters
CREATE OR REPLACE FUNCTION search_properties(
    p_city VARCHAR DEFAULT NULL,
    p_min_rent DECIMAL DEFAULT NULL,
    p_max_rent DECIMAL DEFAULT NULL,
    p_property_type INT DEFAULT NULL,
    p_furnishing INT DEFAULT NULL,
    p_limit INT DEFAULT 20,
    p_offset INT DEFAULT 0
)
RETURNS TABLE (
    "Id" UUID,
    "Title" VARCHAR,
    "Rent" DECIMAL,
    "City" VARCHAR,
    "PropertyType" INT,
    "CoverImage" VARCHAR
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        p."Id",
        p."Title",
        p."Rent",
        p."City",
        p."PropertyType",
        (SELECT pi."ImageUrl" 
         FROM "PropertyImages" pi 
         WHERE pi."PropertyId" = p."Id" 
         AND pi."IsCover" = TRUE 
         LIMIT 1) AS "CoverImage"
    FROM "Properties" p
    WHERE p."Status" = 1
        AND (p_city IS NULL OR p."City" = p_city)
        AND (p_min_rent IS NULL OR p."Rent" >= p_min_rent)
        AND (p_max_rent IS NULL OR p."Rent" <= p_max_rent)
        AND (p_property_type IS NULL OR p."PropertyType" = p_property_type)
        AND (p_furnishing IS NULL OR p."Furnishing" = p_furnishing)
    ORDER BY p."CreatedAt" DESC
    LIMIT p_limit
    OFFSET p_offset;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- STATISTICS QUERIES
-- =====================================================

-- Dashboard statistics
CREATE OR REPLACE VIEW "vw_DashboardStats" AS
SELECT 
    (SELECT COUNT(*) FROM "AspNetUsers") AS "TotalUsers",
    (SELECT COUNT(*) FROM "Properties" WHERE "Status" = 1) AS "ActiveListings",
    (SELECT COUNT(*) FROM "Properties" WHERE "CreatedAt" >= NOW() - INTERVAL '7 days') AS "NewListingsThisWeek",
    (SELECT AVG("Rent") FROM "Properties" WHERE "Status" = 1) AS "AverageRent";

-- =====================================================
-- BACKUP COMMAND
-- =====================================================

-- Create backup:
-- pg_dump -h localhost -U postgres -d roommitra -F c -f roommitra_backup.dump

-- Restore backup:
-- pg_restore -h localhost -U postgres -d roommitra -F c roommitra_backup.dump

-- =====================================================
-- MAINTENANCE
-- =====================================================

-- Vacuum and analyze (run periodically)
-- VACUUM ANALYZE;

-- Reindex (if needed)
-- REINDEX DATABASE roommitra;

-- Check table sizes
-- SELECT 
--     schemaname,
--     tablename,
--     pg_size_pretty(pg_total_relation_size(schemaname||'.'||tablename)) AS size
-- FROM pg_tables
-- WHERE schemaname = 'public'
-- ORDER BY pg_total_relation_size(schemaname||'.'||tablename) DESC;
